name: sweet_chores
description: "Todo-App for make more easy to remind and complete your tasks."
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.4+7

environment:
  sdk: ">=3.2.5 <4.0.0"

# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`.
dependencies:
  art_sweetalert: ^0.0.5
  auto_route: ^7.8.4
  bloc: ^8.1.2
  cached_network_image: ^3.3.1
  connectivity_plus: ^5.0.2
  cupertino_icons: ^1.0.2
  email_validator: ^2.1.17
  equatable: ^2.0.5
  expandable: ^5.0.1
  file_picker: ^6.1.1
  firebase_auth: ^4.16.0
  firebase_core: ^2.24.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_email_sender: ^6.0.2
  flutter_launcher_icons: ^0.13.1
  flutter_localizations:
    sdk: flutter
  flutter_secure_storage: ^9.0.0
  flutter_slidable: ^3.0.1
  flutter_svg: ^2.0.9
  font_awesome_flutter: ^10.7.0
  form_field_validator: ^1.1.0
  get_it: ^7.6.7
  google_fonts: ^6.1.0
  google_sign_in: ^6.2.1
  googleapis: ^12.0.0
  googleapis_auth: ^1.4.1
  http: ^1.2.0
  intl: ^0.18.1
  path_provider: ^2.1.2
  share_extend: ^2.0.0
  sqflite: ^2.3.0

dev_dependencies:
  auto_route_generator: ^7.3.2
  build_runner: ^2.4.8
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo.png"
  min_sdk_android: 21
flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: SweetChores
      fonts:
        - asset: fonts/SweetChores.ttf