// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6mQOuN-ZZCwi7r0ZzJE7X0GVoIwkSXdg',
    appId: '1:1046436470007:web:b609698d78cf04f3d947f2',
    messagingSenderId: '1046436470007',
    projectId: 'sweet-chores',
    authDomain: 'sweet-chores.firebaseapp.com',
    storageBucket: 'sweet-chores.appspot.com',
    measurementId: 'G-SL3EBTPQQB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBphru8opEJfdY9TSKoNcbiEYErMDZhAZQ',
    appId: '1:1046436470007:android:07a1a7b35f3b3114d947f2',
    messagingSenderId: '1046436470007',
    projectId: 'sweet-chores',
    storageBucket: 'sweet-chores.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdQbE2iVWMrVznAN_d2G81q3ZctlDoQBo',
    appId: '1:1046436470007:ios:626711e7d31990a3d947f2',
    messagingSenderId: '1046436470007',
    projectId: 'sweet-chores',
    storageBucket: 'sweet-chores.appspot.com',
    iosBundleId: 'com.example.sweetChoresReloaded',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAdQbE2iVWMrVznAN_d2G81q3ZctlDoQBo',
    appId: '1:1046436470007:ios:b8e5b92ab4c0744cd947f2',
    messagingSenderId: '1046436470007',
    projectId: 'sweet-chores',
    storageBucket: 'sweet-chores.appspot.com',
    iosBundleId: 'com.example.sweetChoresReloaded.RunnerTests',
  );
}
